[tool.flake8]
max_line_length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line_length = 120

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true

[tool.pytest.ini_options]
minversion = "6.0"
python_files = ["test_*.py"]
