name: Audio to Text Whisper Job

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]
    paths:
      - "a2t-whisper/**"

  push:
    branches: ["main"]
    paths:
      - "a2t-whisper/**"

jobs:
  build-test-push-a2t-whisper:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull the latest images for caching
      run: |
        ghcr.io/premai-io/audio-to-text-whisper-tiny-cpu:latest || true
        ghcr.io/premai-io/audio-to-text-whisper-large-v2-gpu:latest || true

    - name: Build the CPU Images
      run: |
        docker buildx create --use
        docker buildx build --push \
          --cache-from ghcr.io/premai-io/audio-to-text-whisper-tiny-cpu:latest \
          --file ./a2t-whisper/docker/cpu/Dockerfile \
          --build-arg="MODEL_ID=tiny" \
          --tag ghcr.io/premai-io/audio-to-text-whisper-tiny-cpu:latest \
          --platform linux/arm64,linux/amd64 ./a2t-whisper
        docker buildx build --push \
          --cache-from ghcr.io/premai-io/audio-to-text-whisper-large-v2-gpu:latest \
          --file ./a2t-whisper/docker/gpu/Dockerfile \
          --build-arg="MODEL_ID=large-v2" \
          --tag ghcr.io/premai-io/audio-to-text-whisper-large-v2-gpu:latest \
          --platform linux/amd64 ./a2t-whisper

    - name: Test the Images
      run: |
        docker run --rm a2t-whisper-tiny-cpu pytest

    - name: Test the Images
      run: |
        docker run --rm a2t-whisper-large-v2-gpu pytest
