name: Audio to Text Whisper Job

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]
    paths:
      - "a2t-whisper/**"

jobs:
  ci-a2t-whisper:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Images
      run: |
        docker buildx build --file ./a2t-whisper/docker/cpu/Dockerfile --build-arg="MODEL_ID=tiny" --tag ghcr.io/premai-io/audio-to-text-whisper-tiny-cpu:latest --tag a2t-whisper-tiny-cpu --platform linux/arm64,linux/amd64 ./a2t-whisper
        docker buildx build --file ./a2t-whisper/docker/gpu/Dockerfile --build-arg="MODEL_ID=large-v2" --tag ghcr.io/premai-io/audio-to-text-whisper-large-v2-gpu:latest --tag a2t-whisper-large-v2-gpu --platform linux/arm64,linux/amd64 ./a2t-whisper

    - name: Test the Images
      run: |
        docker run --rm a2t-whisper-tiny-cpu pytest
        docker run --rm a2t-whisper-large-v2-gpu pytest

    - name: Push the Images
      run: |
        docker push ghcr.io/premai-io/audio-to-text-whisper-tiny-cpu:latest
        docker push ghcr.io/premai-io/audio-to-text-whisper-large-v2-gpu:latest
