name: Coder T5

env:
  VERSION: 0.0.5
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cdr-t5/**"

jobs:
  build-test-push-cdr-t5:
    runs-on: self-hosted-cpu
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./cdr-t5
        push: true
        file: ./cdr-t5/docker/cpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=Salesforce/codet5p-220m-py
        tags: ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest,ghcr.io/premai-io/coder-codet5p-220m-py-cpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest
        cache-to: type=inline

    - name: Test the Images
      run: |
        docker run --rm ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest pytest
