name: Coder Replit

env:
  VERSION: 0.0.2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cdr-replit/**"

jobs:
  build-test-push-cdr-replit:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./cdr-replit
        push: true
        file: ./cdr-replit/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=replit/replit-code-v1-3b
        tags: ghcr.io/premai-io/coder-replit-code-v1-3b-gpu:latest,ghcr.io/premai-io/coder-replit-code-v1-3b-gpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/coder-replit-code-v1-3b-gpu:latest
        cache-to: type=inline

    - name: Test the Images
      run: |
        docker run --rm --gpus all ghcr.io/premai-io/coder-replit-code-v1-3b-gpu:latest pytest
