name: Coder T5

env:
  VERSION: 0.0.5
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cdr-t5/**"

jobs:
  build-test-push-cdr-t5:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push the Images
      run: |
        docker buildx build --push \
            --cache-from ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest \
            --file ./cdr-t5/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=Salesforce/codet5p-220m-py" \
            --tag ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest \
            --tag ghcr.io/premai-io/coder-codet5p-220m-py-cpu:$VERSION \
            --platform linux/amd64 ./cdr-t5

    - name: Test the Images
      run: |
        docker run --rm ghcr.io/premai-io/coder-codet5p-220m-py-cpu:latest pytest
