name: Chat Dolly V2

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]
    paths:
      - "cht-dolly-v2/**"

  push:
    branches: ["main"]
    paths:
      - "cht-dolly-v2/**"

jobs:
  test-cht-dolly-v2:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull the latest images for caching
      run: |
        docker pull ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest || true

    - name: Test the Images
      run: |
        docker build --pull \
          --cache-from ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest \
          --file ./cht-dolly-v2/docker/gpu/Dockerfile \
          --build-arg="MODEL_ID=databricks/dolly-v2-12b" \
          --tag cht-dolly-v2 ./cht-dolly-v2
    - name: Test the Container
      run: |
        docker run --rm --gpus all cht-dolly-v2 pytest

  push-cht-dolly-v2:
    runs-on: gpu
    needs: [test-cht-dolly-v2]
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker buildx create --use
        docker buildx build --push --pull \
          --cache-from ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest \
          --file ./cht-dolly-v2/docker/gpu/Dockerfile \
          --build-arg="MODEL_ID=databricks/dolly-v2-12b" \
          --tag ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest \
          --platform linux/amd64 ./chat-dolly-v2
