name: Chat Dolly v2

env:
  VERSION: 0.0.2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cht-dolly-v2/**"

jobs:
  build-test-push-cht-dolly-v2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./cht-dolly-v2
        push: true
        file: ./cht-dolly-v2/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=databricks/dolly-v2-12b
        tags: ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest,ghcr.io/premai-io/chat-dolly-v2-12b-gpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest
        cache-to: type=inline

    - name: Test the Images
      run: |
        docker run --gpus all ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest pytest
