name: Chat Dolly v2

env:
  VERSION: 1.0.0
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cht-dolly-v2/**"

jobs:
  build-test-push-cht-dolly-v2:
    runs-on: self-hosted-cpu
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      run: |
        docker build \
          --cache-from ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest \
          --file ./cht-dolly-v2/docker/gpu/Dockerfile \
          --build-arg="MODEL_ID=databricks/dolly-v2-12b" \
          --tag ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest \
          --tag ghcr.io/premai-io/chat-dolly-v2-12b-gpu:$VERSION ./cht-dolly-v2
        docker push ghcr.io/premai-io/chat-dolly-v2-12b-gpu:latest
        docker push ghcr.io/premai-io/chat-dolly-v2-12b-gpu:$VERSION
