name: Chat Dolly v2

env:
  VERSION: 0.0.5
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "cht-llama-cpp/**"

jobs:
  build-test-push-cht-llama-cpp:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push the Images
      run: |
        docker buildx build --push \
            --cache-from ghcr.io/premai-io/chat-vicuna-7b-q4-cpu:latest \
            --file ./cht-llama-cpp/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=vicuna-7b-q4" \
            --tag ghcr.io/premai-io/chat-vicuna-7b-q4-cpu:latest \
            --tag ghcr.io/premai-io/chat-vicuna-7b-q4-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./cht-llama-cpp
        docker buildx build --push \
            --cache-from ghcr.io/premai-io/chat-gpt4all-lora-q4-cpu:latest \
            --file ./cht-llama-cpp/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=gpt4all-lora-q4" \
            --tag ghcr.io/premai-io/chat-gpt4all-lora-q4-cpu:latest \
            --tag ghcr.io/premai-io/chat-gpt4all-lora-q4-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./cht-llama-cpp

    - name: Test the Images
      run: |
        docker run --rm ghcr.io/premai-io/chat-vicuna-7b-q4-cpu:latest pytest
