name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    needs: [linter]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run: docker-compose build

      - name: Run APIs Tests
        run: docker-compose run prem_controller pytest ./tests/test_controller.py

      - name: Tear down the Stack
        run: docker-compose down

  push:
    runs-on: ubuntu-latest
    needs: [pytest]
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Images
        run: |
          docker buildx build \
            --push \
            --file ./prem-chat-x/docker/llamacpp/cpu/Dockerfile \
            --build-arg="MODEL_ID=vicuna-7b-q4" \
            --tag ghcr.io/premai-io/prem-chat-vicuna-7b-q4-cpu:latest \
            --platform linux/arm64,linux/amd64 ./prem-chat-x
          docker buildx build \
            --push \
            --file ./prem-chat-x/docker/llamacpp/cpu/Dockerfile \
            --build-arg="MODEL_ID=gpt4all-lora-q4" \
            --tag ghcr.io/premai-io/prem-chat-gpt4all-lora-q4-cpu:latest \
            --platform linux/arm64,linux/amd64 ./prem-chat-x
