name: CI
on:
  push:
  pull_request:
jobs:
  models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: list
      name: List modified models
      run: |
        echo "modified=$(
          for model in $(ls -d *-*); do
            git diff --quiet HEAD~1 -- $model || echo $model
          done | jq -Rsc 'split("\n")[:-1]'
        )" >> $GITHUB_OUTPUT
    outputs:
      modified: ${{ steps.list.outputs.modified }}
  build-test-push:
    needs: [models]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ${{ fromJson(needs.models.outputs.modified) }}
    env:
      VERSION: '1.0.0'
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: ./build.sh ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && '--push' || '--load' }}
      working-directory: ${{ matrix.model }}
      env:
        TESTS_SKIP_GPU: 1
