name: CI

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  linter:
    runs-on: gpu
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: gpu
    needs: [linter]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build and Test the Images for GPU devices
        run: bash ./scripts/build_test_gpu.sh

      - name: Build and Test the Images for Mac M1 devices
        run: bash ./scripts/build_test_m1.sh

  push:
    runs-on: gpu
    needs: [pytest]
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Images
        run: bash ./scripts/build_push.sh
