name: Copilot T5

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]
    paths:
      - "cpl-t5/**"

  push:
    branches: ["main"]
    paths:
      - "cpl-t5/**"

jobs:
  test-cpl-t5:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Build and Push
      run: |
        docker build --file ./cpl-t5/docker/cpu/Dockerfile --build-arg="MODEL_ID=Salesforce/codet5p-220m-py" --tag cpl-t5-cpu ./cpl-t5
        docker run --rm cpl-t5-cpu pytest

  push-cpl-t5:
    runs-on: gpu
    needs: [test-cpl-t5]
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      run: docker buildx build --push --file ./cpl-t5/docker/cpu/Dockerfile --build-arg="MODEL_ID=Salesforce/codet5p-220m-py" --tag ghcr.io/premai-io/copilot-codet5p-220m-py-cpu:latest --platform linux/arm64,linux/amd64 ./cpl-t5
