name: Prem Diffusers

env:
  VERSION: 0.0.6
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "dfs-diffusers/**"

jobs:
  build-test-push-dfs-diffusers:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test the Images
      run: |
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:latest \
            --file ./dfs-diffusers/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=stabilityai/stable-diffusion-2-1-base" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./dfs-diffusers
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:latest \
            --file ./dfs-diffusers/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=stabilityai/stable-diffusion-2-base" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./dfs-diffusers
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-1-5-cpu:latest \
            --file ./dfs-diffusers/docker/cpu/Dockerfile \
            --build-arg="MODEL_ID=runwayml/stable-diffusion-v1-5" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-1-5-cpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-1-5-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./dfs-diffusers


        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:latest \
            --file ./dfs-diffusers/docker/gpu/Dockerfile \
            --build-arg="MODEL_ID=stabilityai/stable-diffusion-2-1-base" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:$VERSION \
            --platform linux/amd64 ./dfs-diffusers
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:latest \
            --file ./dfs-diffusers/docker/gpu/Dockerfile \
            --build-arg="MODEL_ID=stabilityai/stable-diffusion-2-base" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:$VERSION \
            --platform linux/amd64 ./dfs-diffusers
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:latest \
            --file ./dfs-diffusers/docker/gpu/Dockerfile \
            --build-arg="MODEL_ID=runwayml/stable-diffusion-v1-5" \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:latest \
            --tag ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./dfs-diffusers

    - name:
      run: |
        docker run --rm ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:latest pytest
        docker run --rm --gpus all ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:latest pytest
