name: Diffusers Stable Diffusion

env:
  VERSION: 0.0.6
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "dfs-diffusers/**"

jobs:
  build-test-push-dfs-diffusers:
    runs-on: self-hosted-cpu
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/cpu/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: MODEL_ID=stabilityai/stable-diffusion-2-1-base
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-cpu:latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/cpu/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: MODEL_ID=stabilityai/stable-diffusion-2-base
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-2-base-cpu:latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/cpu/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: MODEL_ID=stabilityai/stable-diffusion-v1-5
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-1-5-base-cpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-1-5-base-cpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-1-5-base-cpu:latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=stabilityai/stable-diffusion-v1-5
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-1-5-gpu:latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=stabilityai/stable-diffusion-2-1-base
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-2-1-base-gpu:latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./dfs-diffusers
        push: true
        file: ./dfs-diffusers/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=stabilityai/stable-diffusion-2-base
        tags: ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:latest,ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/diffuser-stable-diffusion-2-base-gpu:latest
