name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Images
        run: |
          docker buildx build \
            --push \
            --file ./prem-chat-x/docker/llamacpp/m1/Dockerfile \
            --build-arg="MODEL_ID=ggml-vicuna-7b-1.1-q4_2" \
            --tag ghcr.io/premai-io/prem-chat-ggml-vicuna-7b-1.1-q4_2-m1:latest \
            --platform linux/arm64,linux/amd64 ./prem-chat-x
          docker buildx build \
            --push \
            --file ./prem-chat-x/docker/llamacpp/m1/Dockerfile \
            --build-arg="MODEL_ID=gpt4all-lora-quantized-ggml" \
            --tag ghcr.io/premai-io/prem-chat-gpt4all-lora-quantized-ggml-m1:latest \
            --platform linux/arm64,linux/amd64 ./prem-chat-x
