name: Embeddings Sentence Transformers

env:
  VERSION: 0.0.5
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "ebd-all-minilm/**"

jobs:
  build-test-push-ebd-all-minilm:
    runs-on: self-hosted-cpu
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./ebd-all-minilm
        push: true
        file: ./ebd-all-minilm/docker/cpu/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: MODEL_ID=all-MiniLM-L6-v2
        tags: ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest,ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest
        cache-to: type=inline

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./ebd-all-minilm
        push: true
        file: ./ebd-all-minilm/docker/gpu/Dockerfile
        platforms: linux/amd64
        build-args: MODEL_ID=all-MiniLM-L6-v2
        tags: ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest,ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpuu:${{ env.VERSION }}
        cache-from: type=registry,ref=ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest
        cache-to: type=inline
