name: Embeddings Sentence Transformers

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]
    paths:
      - "ebd-all-minilm/**"

  push:
    branches: ["main"]
    paths:
      - "ebd-all-minilm/**"

jobs:
  test-ebd-all-minilm:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Test the Images
      run: |
        docker build --file ./ebd-all-minilm/docker/cpu/Dockerfile --build-arg="MODEL_ID=all-MiniLM-L6-v2" --tag ebd-all-minilm-cpu ./ebd-all-minilm
        docker run --rm ebd-all-minilm-cpu pytest

        docker build --file ./ebd-all-minilm/docker/gpu/Dockerfile --build-arg="MODEL_ID=all-MiniLM-L6-v2" --tag ebd-all-minilm-gpu ./ebd-all-minilm
        docker run --rm --gpus all ebd-all-minilm-gpu pytest

  push-ebd-all-minilm:
    runs-on: gpu
    needs: [test-ebd-all-minilm]
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker buildx build --push --file ./ebd-all-minilm/docker/cpu/Dockerfile --build-arg="MODEL_ID=all-MiniLM-L6-v2" --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest --platform linux/arm64,linux/amd64 ./ebd-all-minilm
        docker buildx build --push --file ./ebd-all-minilm/docker/gpu/Dockerfile --build-arg="MODEL_ID=all-MiniLM-L6-v2" --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest --platform linux/amd64 ./ebd-all-minilm
