name: Embeddings Sentence Transformers

env:
  VERSION: 0.0.1
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "ebd-all-minilm/**"
      - "scripts/**"

jobs:
  build-test-push-ebd-all-minilm:
    runs-on: gpu
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull the latest images for caching
      run: |
        docker pull ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest || true
        docker pull ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest || true

    - name: Build the CPU Images
      run: |
        docker buildx create --use
        docker buildx build --push \
          --cache-from ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest \
          --file ./ebd-all-minilm/docker/cpu/Dockerfile \
          --build-arg="MODEL_ID=all-MiniLM-L6-v2" \
          --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest \
          --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:$VERSION \
          --platform linux/arm64,linux/amd64 ./ebd-all-minilm
        docker buildx build --push \
          --cache-from ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest \
          --file ./ebd-all-minilm/docker/gpu/Dockerfile \
          --build-arg="MODEL_ID=all-MiniLM-L6-v2" \
          --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest \
          --tag ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:$VERSION \
          --platform linux/amd64 ./ebd-all-minilm

    - name: Test the CPU Images
      run: |
        docker run --rm ghcr.io/premai-io/embeddings-all-minilm-l6-v2-cpu:latest pytest
        docker run --rm --gpus all ghcr.io/premai-io/embeddings-all-minilm-l6-v2-gpu:latest pytest
