name: Chat Dolly v2

env:
  VERSION: 0.0.5
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "t2a-bark/**"

jobs:
  build-test-push-t2a-bark:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push the Images
      run: |
        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/text-to-audio-bark-cpu:latest \
            --file ./t2a-bark/docker/cpu/Dockerfile \
            --tag ghcr.io/premai-io/text-to-audio-bark-cpu:latest \
            --tag ghcr.io/premai-io/text-to-audio-bark-cpu:$VERSION \
            --platform linux/arm64,linux/amd64 ./t2a-bark

        docker buildx build --push \
            --cache-from=ghcr.io/premai-io/text-to-audio-bark-gpu:latest \
            --file ./t2a-bark/docker/gpu/Dockerfile \
            --tag ghcr.io/premai-io/text-to-audio-bark-gpu:latest \
            --tag ghcr.io/premai-io/text-to-audio-bark-gpu:$VERSION \
            --platform linux/amd64 ./t2a-bark

    - name: Test the Images
      run: |
        docker run --rm ghcr.io/premai-io/text-to-audio-bark-cpu:latest pytest
        docker run --rm --gpus all ghcr.io/premai-io/text-to-audio-bark-gpu:latest pytest
